#Data manipulation in numpy/pandas

## NumPy

**What is NumPy?**

NumPy is the fundamental package for scientific computing in Python. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. 

<br>

**Why NumPy?**

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

The elements in a NumPy array are all required to be of the same data type.

In [0]:
# importing modules
import numpy as np

### Creating np arrays

1-Dimensional array (vector) - My scores for 5 courses

In [0]:
# Create a rank 1 array
scores = np.array([90, 95, 93, 88, 76])
# print array
print(scores)
# type of the object
print(type(scores))   
# shape of the array
print(scores.shape)      

[90 95 93 88 76]
<type 'numpy.ndarray'>
(5,)


Accessing and editing the array

In [0]:
# printing scores of 1st course
print(scores[0])

90


In [0]:
# My scores were incorrectly entered, I scored 65 in the 1st course :(
scores[0] = 65                  

In [0]:
# printing the array
print(scores) 
print(scores[-1])

[65 95 93 88 76]
76


Some Summary statistics

In [0]:
# What's the mean?
print(np.mean(scores))

print(scores.mean())


83.4
83.4


In [0]:
# Max 
print np.max(scores)
# Min
print np.min(scores)

95
65


2-Dimensional array (Matrix)

In [0]:
# Rank 2 array - Scores of 2 of my friends

friends_scores = np.array([[78, 97, 56, 78, 99],
                         [84, 75, 96, 94, 86]])  

In [0]:
# print array
print(friends_scores)

[[78 97 56 78 99]
 [84 75 96 94 86]]


In [0]:
# print shape
print(friends_scores.shape)   

(2, 5)


In [0]:
# How much did my first friend score in the 3rd course?
print(friends_scores[0, 2])

56


### Special values

In [0]:
# Null values
np.nan

nan

In [0]:
np.isnan(np.nan)

True

In [0]:
# Infinity
np.inf

inf

### Slicing

#### 1D array

Syntax is [start:end:by]

In [0]:
# Scores of first 3 subjects
scores = np.array([90, 95, 93, 88, 76])
print scores[:3]  
# scores after 3rd subject
print scores[3:] 
# scores of the 2nd and 3rd subject
print scores[3:5]
# every other score
print scores[::2] 

[90 95 93]
[88 76]
[88 76]
[90 93 76]


In [0]:
# every other score, starting at index 1
scores[1::2]  


array([95, 88])

Indices can be negative as well

In [0]:
scores = np.array([90, 95, 93, 88, 76])
print 'All scores reversed'
print scores[::-1]  
print 'Reversed every other from index 4'
scores[4::-2]  

All scores reversed
[76 88 93 95 90]
Reversed every other from index 4


array([76, 93, 90])

In [0]:
# Second to last element and forward
scores[-2:]

array([88, 76])

You can modify the original vector via slicing

In [0]:
scores = np.array([90, 95, 93, 88, 76])
scores[-2:] = [0,0]
print scores

[90 95 93  0  0]


#### 2D array

Slicing syntax is similar to 1D case, but now you have multiple dimensions to play with

In [0]:
x = np.random.randint(10, size=(3, 4))  # Two-dimensional array
print x
print 'two rows, three columns'
print x[:2, :3]
print 'all rows, every other column'
print x[:3, ::2]  


[[9 7 2 5]
 [9 0 2 7]
 [9 9 1 5]]
two rows, three columns
[[9 7 2]
 [9 0 2]]
all rows, every other column
[[9 2]
 [9 2]
 [9 1]]


Example using negative indexing

In [0]:
print x
print 'Reversed together'
print x[::-1, ::-1]


[[9 7 2 5]
 [9 0 2 7]
 [9 9 1 5]]
Reversed together
[[5 1 9 9]
 [7 2 0 9]
 [5 2 7 9]]


Accessing rows and columns

In [0]:
print x
print 'First column of x2'
print x[:, 0] 
print 'First row of x2'
print(x[0, :])
print 'Another way'
print(x[0])

[[9 7 2 5]
 [9 0 2 7]
 [9 9 1 5]]
First column of x2
[9 9 9]
First row of x2
[9 7 2 5]
Another way
[9 7 2 5]


### Matrix/Vector Operations

Dot product:
`np.dot(a, b)` where a and b are ndarrays

In [0]:
# Scores of 2 of my friends on 5 tests
scores = np.array([90, 95, 93, 88, 76])
# Mean score
print np.dot(scores,
             np.array([0.2, 0.2, 0.2, 0.2, 0.2]))

88.4


Matrix multiplication: `np.matmul(a, b)`

In [0]:
friends_scores = np.array([[78, 97, 56, 78, 99],
                         [84, 75, 96, 94, 86]]) 
# Average scores per test
print np.matmul(np.array([0.5, 0.5]), friends_scores)


[ 81.   86.   76.   86.   92.5]


Element-wise operations

In [0]:
# Another way of computing average scores per test
friends_scores = np.array([[78, 97, 56, 78, 99],
                         [84, 75, 96, 94, 86]])
# Average scores per test
print (friends_scores[0, :] + friends_scores[1, :]) / (
    np.array([2., 2., 2., 2., 2.]))

# It turns out the following also works because of broadcasting
# (covered next)
print (friends_scores[0, :] + friends_scores[1, :]) / 2.



[ 81.   86.   76.   86.   92.5]
[ 81.   86.   76.   86.   92.5]


### Broadcasting

* If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. 
* Operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability.
* The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

Example: Let's count calories in foods using a macro-nutrient breakdown. Roughly put, the caloric parts of food are made of fats , protein (4 calories per gram) and carbs (4 calories per gram).  So if we list some foods (our data), and for each food list its macro-nutrient breakdown (parameters), we can then multiply each nutrient by its caloric value (apply scaling) to compute the caloric breakdown of each food item.

* Example: 
 * We have Grams for each food broken down by fat, protein, and carbs
  * We have Calories per gram broken down by fat, protein, and carbs
  * We want Calories for each food broken down by fat, protein, carbs


In [0]:
# Grams for each food broken down by fat, protein, and carbs
grams_in_foods = np.array([
  [0.3, 2.5, 3.5],  # Brocolli contains 0.3g fat, 2.5g protein and 3.5g carbs
  [2.9, 27.5, 0],   # Chicken breast contains 2.9g fat, 27.5g protein and 0g carbs
  [0.4, 1.3, 23.9], # and so on..
  [14.4, 6, 2.3]])
# Calories per gram broken down by fat, protein, and carbs
cal_per_gram = np.array([9, 4, 4])
# Calories for each food broken down by fat, protein, carbs
calories_in_foods = grams_in_foods * cal_per_gram
print calories_in_foods

[[   2.7   10.    14. ]
 [  26.1  110.     0. ]
 [   3.6    5.2   95.6]
 [ 129.6   24.     9.2]]


Implementation using element-wise multiplication without broadcasting

In [0]:
# Create a new array filled with zeros, of the same shape as macros.
result = np.zeros_like(grams_in_foods)

# Now multiply each row of macros by cal_per_macro. In Numpy, `*` is
# element-wise multiplication between two arrays.
for i in xrange(grams_in_foods.shape[0]):
  result[i, :] = grams_in_foods[i, :] * cal_per_gram

result

array([[   2.7,   10. ,   14. ],
       [  26.1,  110. ,    0. ],
       [   3.6,    5.2,   95.6],
       [ 129.6,   24. ,    9.2]])

### Basic operations

In [0]:
# vstack, hstack
friends_scores = np.array([[78, 97, 56, 78, 99],
                         [84, 75, 96, 94, 86]])  
scores = np.array([90, 95, 93, 88, 76])
np.vstack([scores, friends_scores])

array([[90, 95, 93, 88, 76],
       [78, 97, 56, 78, 99],
       [84, 75, 96, 94, 86]])

In [0]:
# transpose
friends_scores.T

array([[78, 84],
       [97, 75],
       [56, 96],
       [78, 94],
       [99, 86]])

In [0]:
# concatenate - throws an error, can you guess why?
np.concatenate((scores, friends_scores))

ValueError: ignored

In [0]:
np.concatenate((scores, friends_scores[0], friends_scores[1]))

array([90, 95, 93, 88, 76, 78, 97, 56, 78, 99, 84, 75, 96, 94, 86])

In [0]:
print 'Create matrix of ones'
print np.ones((4,5))
print 'Create matrix of zeros'
print np.zeros((3, 2))

Create matrix of ones
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
Create matrix of zeros
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


### Exercise

Find the ordinary least squares solution for the beta coefficients manually using the closed-form formula and write this as a function:

inv(X^TX) X^Ty

In [0]:
import numpy as np
y = np.array([1, 2, 3, 4, 5, 6, 7, 8]).T
x = np.array([[1, 1], [2, 1], [3, 1], [3, 1], [3, 1],
             [6, 1], [6, 2], [7, 1]])

In [0]:
def FindLinearRegressionCoefficients(x, y):
  betas = np.matmul(np.linalg.inv(np.matmul(x.T, x)),
                    np.matmul(x.T, y))
  return betas

In [0]:
FindLinearRegressionCoefficients(x, y)

array([ 1.06369427,  0.33121019])

In [0]:
FindLinearRegressionCoefficients(np.array([[8,1], [1,1], [1,1]]),
                                 np.array([9, 2, 4]).T)

array([ 0.85714286,  2.14285714])

In [0]:
def FindLinearRegressionCoefficients(x, y):
  try:
    betas = np.matmul(np.linalg.inv(np.matmul(x.T, x)),
                      np.matmul(x.T, y))
  except np.linalg.LinAlgError:
    betas = [np.nan, np.nan]
  return betas

## Pandas

In [0]:
import pandas as pd
import numpy as np

**Core components of pandas: Series and DataFrames**: 

The primary two components of pandas are the Series and DataFrame. A Series is essentially a column, and a DataFrame is a multi-dimensional table made up of a collection of Series.

### Reading from a csv

In [0]:
from google3.pyglib import gfile
df = pd.read_csv(gfile.GFile("/cns/vq-d/home/menjoge/coauthor/example.csv"))

In [0]:
df.head()

Email PreferredLanguage
0     rajiv.menjoge@gmail.com            python
1             rajiv@yahoo.com            Python
2       somegoogler@gmail.com                 R
3         menjoge@hotmail.com               C++
4  rajiv@alum.somecollege.org                 R

### Converting pandas to ndarray

In [0]:
print 'Full df'
print df.values
print 'One column'
emails = df['Email'].values
print emails
multicolumn = df[['Email', 'PreferredLanguage']].values
print 'Multicolumn'
print multicolumn

Full df
[['rajiv.menjoge@gmail.com' 'python']
 ['rajiv@yahoo.com' 'Python']
 ['somegoogler@gmail.com' 'R']
 ['menjoge@hotmail.com' 'C++']
 ['rajiv@alum.somecollege.org' 'R']
 ['menjoge@something.com' 'Python']]
One column
['rajiv.menjoge@gmail.com' 'rajiv@yahoo.com' 'somegoogler@gmail.com'
 'menjoge@hotmail.com' 'rajiv@alum.somecollege.org' 'menjoge@something.com']
Multicolumn
[['rajiv.menjoge@gmail.com' 'python']
 ['rajiv@yahoo.com' 'Python']
 ['somegoogler@gmail.com' 'R']
 ['menjoge@hotmail.com' 'C++']
 ['rajiv@alum.somecollege.org' 'R']
 ['menjoge@something.com' 'Python']]


### Reshaping

In [0]:
emails = df['Email'].values
print emails.shape
emails = np.reshape(emails, (6,1))
print emails.shape

(6,)
(6, 1)


### Other ways of creating dataframes

In [0]:
# Creating a Series by passing a list of values, letting pandas create a default integer index:

s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [0]:
# Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns:

dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.557141 -0.321189 -0.582426  0.675692
2013-01-02 -0.653942  0.545239 -1.204528 -0.582420
2013-01-03 -0.860447  1.121019  0.920419  1.304150
2013-01-04  1.131651  0.098611  0.453361  0.602169
2013-01-05 -0.098668  0.816264  0.140257 -0.400172
2013-01-06 -0.458456 -1.356843  0.665047  1.386279

In [0]:
# Creating a DataFrame by passing a dict of objects that can be converted to series-like.

df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [0]:
# The columns of the resulting DataFrame have different dtypes.
 df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [0]:
# Creating a DataFrame by loading a csv/json

In [0]:
# Writing a csv/json

### Viewing data

In [0]:
df.head(4) # default is 5

A         B         C         D
2013-01-01  0.557141 -0.321189 -0.582426  0.675692
2013-01-02 -0.653942  0.545239 -1.204528 -0.582420
2013-01-03 -0.860447  1.121019  0.920419  1.304150
2013-01-04  1.131651  0.098611  0.453361  0.602169

In [0]:
df.tail(3)

A         B         C         D
2013-01-04  1.131651  0.098611  0.453361  0.602169
2013-01-05 -0.098668  0.816264  0.140257 -0.400172
2013-01-06 -0.458456 -1.356843  0.665047  1.386279

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2013-01-01 to 2013-01-06
Freq: D
Data columns (total 4 columns):
A    6 non-null float64
B    6 non-null float64
C    6 non-null float64
D    6 non-null float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [0]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.063787  0.150517  0.065355  0.497616
std    0.768707  0.898692  0.809833  0.831308
min   -0.860447 -1.356843 -1.204528 -0.582420
25%   -0.605071 -0.216239 -0.401755 -0.149587
50%   -0.278562  0.321925  0.296809  0.638930
75%    0.393189  0.748507  0.612125  1.147036
max    1.131651  1.121019  0.920419  1.386279

In [0]:
df.shape

(6, 4)

In [0]:
df.columns.values

array(['A', 'B', 'C', 'D'], dtype=object)

### Slicing

In [0]:
# Selecting a single column, which yields a Series, equivalent to df.A:
df['A']

2013-01-01    0.557141
2013-01-02   -0.653942
2013-01-03   -0.860447
2013-01-04    1.131651
2013-01-05   -0.098668
2013-01-06   -0.458456
Freq: D, Name: A, dtype: float64

In [0]:
# Selecting via [], which slices the rows.
df[0:3]

A         B         C         D
2013-01-01  0.557141 -0.321189 -0.582426  0.675692
2013-01-02 -0.653942  0.545239 -1.204528 -0.582420
2013-01-03 -0.860447  1.121019  0.920419  1.304150

In [0]:
# For getting a cross section using a label:
df.loc['2013-01-01']

A    0.557141
B   -0.321189
C   -0.582426
D    0.675692
Name: 2013-01-01 00:00:00, dtype: float64

In [0]:
# Selecting on a multi-axis by label:
df.loc[:, ['A', 'B']]

A         B
2013-01-01  0.557141 -0.321189
2013-01-02 -0.653942  0.545239
2013-01-03 -0.860447  1.121019
2013-01-04  1.131651  0.098611
2013-01-05 -0.098668  0.816264
2013-01-06 -0.458456 -1.356843

In [0]:
# Select via the position of the passed integers:
df.iloc[0]

A    0.557141
B   -0.321189
C   -0.582426
D    0.675692
Name: 2013-01-01 00:00:00, dtype: float64

In [0]:
# By lists of integer position locations, similar to the numpy/python style:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2013-01-02 -0.653942 -1.204528
2013-01-03 -0.860447  0.920419
2013-01-05 -0.098668  0.140257

In [0]:
# For slicing columns explicitly:
df.iloc[:, 1:3]


B         C
2013-01-01 -0.321189 -0.582426
2013-01-02  0.545239 -1.204528
2013-01-03  1.121019  0.920419
2013-01-04  0.098611  0.453361
2013-01-05  0.816264  0.140257
2013-01-06 -1.356843  0.665047

In [0]:
# Boolean indexing
# Using a single column’s values to select data.

df[df.A > 0]

A         B         C         D
2013-01-01  0.557141 -0.321189 -0.582426  0.675692
2013-01-04  1.131651  0.098611  0.453361  0.602169

In [0]:
# Selecting values from a DataFrame where a boolean condition is met.

df[df > 0]

A         B         C         D
2013-01-01  0.557141       NaN       NaN  0.675692
2013-01-02       NaN  0.545239       NaN       NaN
2013-01-03       NaN  1.121019  0.920419  1.304150
2013-01-04  1.131651  0.098611  0.453361  0.602169
2013-01-05       NaN  0.816264  0.140257       NaN
2013-01-06       NaN       NaN  0.665047  1.386279

In [0]:
# Using the isin() method for filtering:

df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2013-01-01  0.557141 -0.321189 -0.582426  0.675692    one
2013-01-02 -0.653942  0.545239 -1.204528 -0.582420    one
2013-01-03 -0.860447  1.121019  0.920419  1.304150    two
2013-01-04  1.131651  0.098611  0.453361  0.602169  three
2013-01-05 -0.098668  0.816264  0.140257 -0.400172   four
2013-01-06 -0.458456 -1.356843  0.665047  1.386279  three

In [0]:
df2[df2['E'].isin(['two', 'four'])]

A         B         C         D     E
2013-01-03 -0.860447  1.121019  0.920419  1.304150   two
2013-01-05 -0.098668  0.816264  0.140257 -0.400172  four

### Setting values

In [0]:
# dropping a column
df2 = df2.drop("E", axis=1)

In [0]:
df.loc[:, 'D'] = np.array([5] * len(df))

In [0]:
df2[df2 > 0] = df2
df2

A         B         C         D
2013-01-01  0.557141 -0.321189 -0.582426  0.675692
2013-01-02 -0.653942  0.545239 -1.204528 -0.582420
2013-01-03 -0.860447  1.121019  0.920419  1.304150
2013-01-04  1.131651  0.098611  0.453361  0.602169
2013-01-05 -0.098668  0.816264  0.140257 -0.400172
2013-01-06 -0.458456 -1.356843  0.665047  1.386279

### Missing values

In [0]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

A         B         C  D    E
2013-01-01  0.557141 -0.321189 -0.582426  5  1.0
2013-01-02 -0.653942  0.545239 -1.204528  5  1.0
2013-01-03 -0.860447  1.121019  0.920419  5  NaN
2013-01-04  1.131651  0.098611  0.453361  5  NaN

In [0]:
# To drop any rows that have missing data
df1.dropna(how='any')

A         B         C  D    E
2013-01-01  0.557141 -0.321189 -0.582426  5  1.0
2013-01-02 -0.653942  0.545239 -1.204528  5  1.0

In [0]:
# Filling missing data.
df1.fillna(value=5)

A         B         C  D    E
2013-01-01  0.557141 -0.321189 -0.582426  5  1.0
2013-01-02 -0.653942  0.545239 -1.204528  5  1.0
2013-01-03 -0.860447  1.121019  0.920419  5  5.0
2013-01-04  1.131651  0.098611  0.453361  5  5.0

In [0]:
# To get the boolean mask where values are nan.

pd.isna(df1)

A      B      C      D      E
2013-01-01  False  False  False  False  False
2013-01-02  False  False  False  False  False
2013-01-03  False  False  False  False   True
2013-01-04  False  False  False  False   True

### Apply and Lambda functions

In [0]:
# To get the boolean mask where values are nan.
df.apply(np.cumsum)

A         B         C   D
2013-01-01  0.557141 -0.321189 -0.582426   5
2013-01-02 -0.096801  0.224049 -1.786953  10
2013-01-03 -0.957248  1.345068 -0.866534  15
2013-01-04  0.174403  1.443680 -0.413174  20
2013-01-05  0.075735  2.259944 -0.272917  25
2013-01-06 -0.382721  0.903101  0.392130  30

In [0]:
df.apply(lambda x: x.max() - x.min())

A    1.992098
B    2.477862
C    2.124946
D    0.000000
dtype: float64

### Merge/Concat/Join

Concatenate

In [0]:
# Concatenating pandas objects together with concat():

df = pd.DataFrame(np.random.randn(10, 4))

# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

0         1         2         3
0  0.319253  0.128411 -0.790986 -1.281175
1 -0.462498  0.083240  0.815860 -0.411954
2 -0.014330 -2.086874 -1.254683  1.693431
3 -1.150157  0.745004 -1.091509 -1.160350
4 -0.245200 -1.020127  0.004363 -2.704868
5  0.803590 -0.654982  0.436075 -0.241804
6  1.809310 -0.489750  1.105466  0.377052
7 -0.166986 -1.024829  0.637974 -0.188694
8  1.446345 -1.148157  0.186696 -0.061227
9  0.474694  0.562775 -0.136885  0.027299

Joins

In [0]:
# SQL style merges. See the Database style joining section.

left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})

right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

In [0]:
left

key  lval
0  foo     1
1  foo     2

In [0]:
right

key  rval
0  foo     4
1  foo     5

In [0]:
pd.merge(left, right, on='key')

key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

Append

In [0]:
#Append rows to a dataframe. 

df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])

df.head()

A         B         C         D
0  1.871247 -0.239678  0.066924  0.274989
1  0.356630  0.746998  0.808299  0.085506
2 -0.486247 -1.146083  0.149665  0.078882
3 -0.029688  0.728660 -0.212703 -0.382280
4  0.498091  0.435516  0.944673  0.103959

In [0]:
s = df.iloc[3]
s

A   -0.029688
B    0.728660
C   -0.212703
D   -0.382280
Name: 3, dtype: float64

In [0]:
df.append(s, ignore_index=True)

A         B         C         D
0  1.871247 -0.239678  0.066924  0.274989
1  0.356630  0.746998  0.808299  0.085506
2 -0.486247 -1.146083  0.149665  0.078882
3 -0.029688  0.728660 -0.212703 -0.382280
4  0.498091  0.435516  0.944673  0.103959
5  0.590629 -0.862423 -0.836036  0.129990
6  1.077152  0.414135  1.088877 -1.058313
7 -0.422634  0.188583  1.994744  0.023805
8 -0.029688  0.728660 -0.212703 -0.382280

### Grouping

In [0]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                         'foo', 'bar', 'foo', 'foo'],
                     'B': ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                     'C': np.random.randn(8),
                      'D': np.random.randn(8)})
  

df

A      B         C         D
0  foo    one  0.738991 -1.157076
1  bar    one -1.642185 -0.591463
2  foo    two -0.290391  0.323696
3  bar  three  1.635527 -0.731279
4  foo    two  0.406602 -1.831752
5  bar    two  1.123846 -1.065699
6  foo    one -0.353764 -0.657090
7  foo  three  0.579192 -1.071797

In [0]:
df.groupby('A').sum()

C         D
A                      
bar  1.117188 -2.388441
foo  1.080631 -4.394020

In [0]:
df.groupby(['A', 'B']).sum()


C         D
A   B                        
bar one   -1.642185 -0.591463
    three  1.635527 -0.731279
    two    1.123846 -1.065699
foo one    0.385227 -1.814166
    three  0.579192 -1.071797
    two    0.116211 -1.508057

### Miscellaneous

Sort values

In [0]:
df.head()

A      B         C         D
0  foo    one  0.738991 -1.157076
1  bar    one -1.642185 -0.591463
2  foo    two -0.290391  0.323696
3  bar  three  1.635527 -0.731279
4  foo    two  0.406602 -1.831752

In [0]:
#Let's sort the data frame by ounces - inplace = True will make changes to the data
df.sort_values(by=['A', 'C'],ascending=[True, False],inplace=False)

A      B         C         D
1  bar    one -1.642185 -0.591463
5  bar    two  1.123846 -1.065699
3  bar  three  1.635527 -0.731279
6  foo    one -0.353764 -0.657090
2  foo    two -0.290391  0.323696
4  foo    two  0.406602 -1.831752
7  foo  three  0.579192 -1.071797
0  foo    one  0.738991 -1.157076

Duplicates

In [0]:
#create another dataframe with duplicated rows
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [0]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [0]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

Renaming columns

In [0]:
data.rename(columns = {"k1":"kay", "k2":"kay2"})

kay  kay2
0  one     3
1  one     2
2  one     1
3  two     3
4  two     3
5  two     4
6  two     4